### ISSUE TITLE
Testing on various devices 

### ISSUE THREAD

**Issue by hannesrunersjo** [Simumatik/usability-test#1]
Which devices should we focus on during the tests? @MikelAyani just bought a chromebook for the company so we can test pc as well as a tablet.

**Comment by hannesrunersjo** [comment]
I would suggest we do the testing on a laptop, that way we can be quite flexible with where we perform the tests, we can use my laptop for that. I can include a computer mouse so that we have that as a support. Then either during the same test, or if we do more tests we can let them use the Chromebook. To test the touch support of the platform.

**Comment by MikelAyani** [comment]
I would say that we should combine the tests between our gaming laptop and the Chromebook. The first has much better performance and bigger screen size, while the other is small and in addition has the touch screen and can be used as a tablet.

**Comment by hannesrunersjo** [comment]
Sounds good! If we do physical lab tests then we have the devices!
